name: build site

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous workflow runs
        uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Declare env variables
        if: github.event_name == 'push'
        shell: bash
        run: |
          echo "BRANCH_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
            python-version: 3.9

      - name: Upgrade PIP
        run: python -m pip install --upgrade pip

      - name: Install Sphinx dependences
        run: python -m pip install sphinx sphinx-book-theme myst-nb seaborn 'jinja2<3.1'

      - name: Install EasyDiffraction dependences
        run: |
#          python -m pip install easyDiffraction --extra-index-url https://easyscience.github.io/pypi
          python -m pip install git+https://github.com/easyScience/easyDiffractionLib.git@minor-fixes --extra-index-url https://easyscience.github.io/pypi
          python -m pip install CFML
          python -m pip install emcee
          python -m pip install py3Dmol bokeh

      - name: Build site
        continue-on-error: true
        run: sphinx-build -j 4 -nW --keep-going -b html content/ public/

      - name: Deploy built site to 'public_...' branch
        uses: s0/git-publish-subdir-action@develop
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          REPO: self
          BRANCH: public_${{ env.BRANCH_NAME }}
          FOLDER: public
