name: Build static site

on: push

env:
 CI_BRANCH: more-examples  # ${{ github.head_ref || github.ref_name }}

jobs:
  build-site:
    runs-on: macos-14

    steps:
      - name: Cancel previous workflow runs
        uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Declare env variables
        if: github.event_name == 'push'
        shell: bash
        run: |
          echo "BRANCH_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # Activate dark mode to create documentation with Plotly charts in dark mode
      # Need a better solution to automatically switch the chart colour theme based on the mkdocs material switcher
      # Something similar to mkdocs_plotly_plugin https://haoda-li.github.io/mkdocs-plotly-plugin/,
      # but for generating documentation from notepads
      - name: Activate dark mode
        run: |
          brew install dark-mode
          dark-mode status
          dark-mode on
          dark-mode status

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
            python-version: 3.12

      - name: Upgrade package installer for Python
        run: python -m pip install --upgrade pip

      - name: Install Python dependences
        run: |
          pip install mkdocs-material mkdocs-jupyter
          pip install 'easydiffraction[charts] @ git+https://github.com/EasyScience/EasyDiffractionLib@more-examples'

      - name: Download Jupyter notebooks from EasyDiffractionLib
        run: |
          cd docs/
          curl https://codeload.github.com/easyscience/EasyDiffractionLib/tar.gz/more-examples | tar -xz --strip=1 EasyDiffractionLib-more-examples/examples

      - name: Import easydiffraction  # to avoid import info from matplotlib during build
        run: python -c "import easydiffraction"

      - name: Build site
        run: mkdocs build

      - name: Deploy built site to 'public_...' branch
        uses: s0/git-publish-subdir-action@develop
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          REPO: self
          BRANCH: public_${{ env.BRANCH_NAME }}
          FOLDER: site
