name: Build static site

# Trigger the workflow on push events
on: push

env:
  # Set environment variable for the branch name
  # NOTE: Use the same branch name as the one of EasyDiffractionLib. This is
  # required to download the Jupyter notebooks from the EasyDiffractionLib repository
  CI_BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:

  # Job 1: Build the static files for the documentation site
  build-docs:

    runs-on: macos-14  # Use macOS to switch to dark mode for Plotly charts

    steps:
      - name: Cancel previous workflow runs
        uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Activate dark mode to create documentation with Plotly charts in dark mode
      # Need a better solution to automatically switch the chart colour theme based on the mkdocs material switcher
      # Something similar to mkdocs_plotly_plugin https://haoda-li.github.io/mkdocs-plotly-plugin/,
      # but for generating documentation from notepads
      - name: Activate dark mode
        run: |
          brew install dark-mode
          dark-mode status
          dark-mode on
          dark-mode status

      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
            python-version: '3.12'

      # Install MkDocs -- static site generator
      # https://www.mkdocs.org
      - name: Install MkDocs and its dependencies
        run: pip install mkdocs mkdocs-material mkdocs-jupyter

      # Install EasyDiffractionLib to run Jupyter notebooks
      # Install with the [charts] extra
      # Install from the same branch as the current one (CI_BRANCH)
      - name: Install EasyDiffractionLib and its dependencies
        run: pip install 'easydiffraction[charts] @ git+https://github.com/EasyScience/EasyDiffractionLib@${{ env.CI_BRANCH }}'

      # Download Jupyter notebooks from EasyDiffractionLib to the examples folder
      # The notebooks are used to generate the documentation
      # Download from the same branch as the current one (CI_BRANCH)
      - name: Download Jupyter notebooks from EasyDiffractionLib
        run: |
          cd docs/
          curl https://codeload.github.com/easyscience/EasyDiffractionLib/tar.gz/${{ env.CI_BRANCH }} | tar -xz --strip=1 EasyDiffractionLib-${{ env.CI_BRANCH }}/examples

      # The following step is needed to avoid the following message during the build:
      # "Matplotlib is building the font cache; this may take a moment"
      - name: Initial import of easydiffraction
        run: python -c "import easydiffraction"

      # Build the static files
      # Input: docs/ directory containing the Markdown files
      # Output: site/ directory containing the generated HTML files
      - name: Build site with MkDocs
        run: mkdocs build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Upload the static files from the site/ directory to be used in the next job
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/
